fails:Kernel#callcc is possible to exit a loop like a break
fails:Kernel#callcc is possible to call a continuation multiple times
fails:Kernel#callcc returns the arguments to call
fails:Kernel#callcc preserves changes to block-local scope
fails:Kernel#callcc preserves changes to method-local scope
fails:Kernel#callcc raises a LocalJumpError if callcc is not given a block
critical:Kernel#callcc returns the results of continuation once called
fails:Kernel#callcc returns the results of a block if continuation is not called
