fails:Hash#rehash causes a RuntimeError to be raised if called inside an iterator block
