fails:Kernel.throw raises an ArgumentError if there is no catch block for the symbol
